CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');

CREATE TABLE user_data(
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'USER'
);